import os, sys
from datetime import datetime
from starlette.testclient import TestClient
from fasthtml.common import database
from bs4 import BeautifulSoup

# In order to import the app from the main module, we need to add the parent directory to the system path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from main import app

db = database("data/quran.db")
revisions = db.t.revisions
initial_revisions_count = len(revisions())

DUMMY_PAGE = 1000000  # This is a dummy page number for testing purposes
current_date = datetime.now().strftime("%Y-%m-%d")
client = TestClient(app)


# Dummy page is used to retrive the page data because `id` is auto generated by DB
def get_dummy_page_data() -> dict:
    return revisions(where=f"page = {DUMMY_PAGE}")[0]


# This function is used to check the total number of rows
def check_total_number_of_rows():
    response = client.get("/revision")
    # Parse the HTML to easily count the number of rows
    soup = BeautifulSoup(response.text, "html.parser")
    tbody = soup.find("tbody")
    return len(tbody.find_all("tr"))


########################### Tests ###########################
# This route is responsible for handling navigation
# As we are using a single textbox for bulk entry and single entry.
def test_entry_route():
    response = client.post(
        "/revision/entry",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        data={
            "type": "single",
            "page": "56",
        },
    )
    assert response.status_code == 200


def test_decimal_value_on_entry_route():
    response = client.post(
        "/revision/entry",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        data={
            "type": "single",
            "page": "56.20",
        },
    )
    assert response.status_code == 200


def test_total_number_of_rows():
    assert initial_revisions_count == check_total_number_of_rows()


def test_create_landing_route():
    response = client.get("/revision/add?page=56")
    assert response.status_code == 200


def test_create_page():
    response = client.post(
        "/revision/add",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        data={
            "id": "",
            "user_id": "1",
            "page": DUMMY_PAGE,
            "revision_date": current_date,
            "rating": 1,
        },
    )
    assert response.status_code == 200
    # TODO: which is the best way to check if the page was added
    # one is against the UI, the other is against the DB
    assert (initial_revisions_count + 1) == check_total_number_of_rows()
    # assert (initial_revisions_count + 1) == len(revisions())


def test_update_landing_route():
    id = get_dummy_page_data()["id"]
    response = client.get(f"/revision/edit/{id}")
    assert response.status_code == 200


def test_update_page():
    page_data = get_dummy_page_data()
    page_data["rating"] = -1  # Update the rating

    response = client.post(
        "/revision/edit",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        data=page_data,
    )
    assert response.status_code == 200
    assert revisions[page_data["id"]]["rating"] == -1  # Check if the rating was updated
    # Check if the page is still present
    assert (initial_revisions_count + 1) == check_total_number_of_rows()
    # assert (initial_revisions_count + 1) == len(revisions())


def test_delete_page():
    id = get_dummy_page_data()["id"]

    response = client.delete(f"/revision/delete/{id}")
    assert response.status_code == 200
    # Check if the page was deleted
    assert initial_revisions_count == check_total_number_of_rows()
    # assert initial_revisions_count == len(revisions())
